### ISSUE TITLE
support for nested folder

### ISSUE THREAD

**Issue by Tudyx** [willcrichton/mdbook-quiz#11]
Currently if we put a quiz in a nested folder, that doesn't seem to work.
I've created a minimal example here: https://github.com/Tudyx/mdbookquiz-nested-folder

That's already super great to have quiz in flat book but it is planned to add support for nested one in the future?

I think it will be a good use case because the [mdbook doc is kind of encouraging to have a nested structure](https://rust-lang.github.io/mdBook/guide/creating.html#summarymd).

**Comment by Tudyx** [comment]
Unfortunately  its seems that the [fix commit](https://github.com/willcrichton/mdbook-quiz/commit/7a9f135c4ab4d6602cdaa2ad241b86b2ae0e5fa6) wasn't added to the main branch

**Comment by willcrichton** [comment]
The content of the commit has there -- the specific commit may have gotten deleted during some rebasing.
https://github.com/willcrichton/mdbook-quiz/blob/main/src/processor.rs#L143-L159

**Comment by Tudyx** [comment]
Oh sorry I had not seen that. Thanks for the fix!
