### ISSUE TITLE
quiz doesn't show up  when we put a code block at the end of the file

### ISSUE THREAD

**Issue by Tudyx** [willcrichton/mdbook-quiz#13]
Thanks for your work. I've noticed that the quiz doesn't show up  when we put a code block at the end of the file (with no blanket line after).

For instance, if we add this line to *chapter_1.md* of the [example](https://github.com/willcrichton/mdbook-quiz/blob/main/example/src/chapter_1.md) of this repository: 

```rust
println("hello world");
```
I can't show the full content of the file because it won't display well on this issue, but you can find a repository that reproduces the bug [here](https://github.com/Tudyx/mdbookquiz-nested-folder/blob/main/src/chapter_1.md).

**Comment by willcrichton** [comment]
Thanks for the report. This will be fixed in the 0.2.4 minor release.
