### ISSUE TITLE
Enable random order in answers

### ISSUE THREAD

**Issue by driftavalii** [willcrichton/mdbook-quiz#2]
This is more of a feature request, the current display always provides multiple choice answers in the same order, would it be possible to randomize the answers? Providing the right answer might then become challenging though, but a map could be used instead of an array for the answers?

**Comment by willcrichton** [comment]
This would be possible. Currently the `QuestionMethods` interface doesn't allow for question-level state to be propagated between each view, but that could be changed with enough work.
