### ISSUE TITLE
Support checkbox in addition to radio button for multiplechoice answers

### ISSUE THREAD

**Issue by driftavalii** [willcrichton/mdbook-quiz#3]
Currently, you can only choose one possible solution as the answer, would it be possible to support the selection of multiple choices as the answer?

**Comment by willcrichton** [comment]
That would certainly be possible, such a contribution is welcome. I think you could change the `MultipleChoice.answer` field to be of type `number | number[]` and change the `MultipleChoice` view accordingly.
