### ISSUE TITLE
Provid more context when error is thrown

### ISSUE THREAD

**Issue by Tudyx** [willcrichton/mdbook-quiz#8]
I'm trying to use the quizz inside my `mdbook` but sadly I'm panicking at this line:

https://github.com/willcrichton/mdbook-quiz/blob/main/src/processor.rs#L207

I think maybe we could have some context to the error, for instance the variable `chapter` to make it easier to debug.

**Comment by Tudyx** [comment]
I propose a solution for my problem here https://github.com/willcrichton/mdbook-quiz/pull/10

**Comment by willcrichton** [comment]
Closed by #10.
