### ISSUE TITLE
adding supporte for draft chapter

### ISSUE THREAD

**Issue by Tudyx** [willcrichton/mdbook-quiz#9]
`mdbook` allows you to define [draft chapter](https://rust-lang.github.io/mdBook/format/summary.html#structure) in your summary.

But currently if you have a draft chapter and we use `mdbook-quiz` we panic because of this line https://github.com/willcrichton/mdbook-quiz/blob/main/src/processor.rs#L207

As a minimal reproduction case, we can simply use the [example](https://github.com/willcrichton/mdbook-quiz/tree/main/example) provided in this repository and add this line to *SUMMARY.md* : 

```md
# Summary

- [Chapter 1](./chapter_1.md)
- [Chapter 2]()
``` 

I think the simple fix would be doing only treat the case were the option is `Some` using a` if let Some` construct.

**Comment by willcrichton** [comment]
Closed by #10.
